agrega verificación para asegurar que OpenVPN se inicie correctamente antes de continuar con la conexión SSH y el despliegue

diff --git a/.github/workflows/test_deploy_faceubb.yml b/.github/workflows/test_deploy_faceubb.yml
--- a/.github/workflows/test_deploy_faceubb.yml
+++ b/.github/workflows/test_deploy_faceubb.yml
@@ -45,6 +45,10 @@ jobs:
         run: |
           sudo openvpn --config face-ubb.ovpn --auth-user-pass <(echo -e "${{ secrets.OPENVPN_USERNAME }}\n${{ secrets.OPENVPN_PASSWORD }}") --daemon
           sleep 15 # Espera a que la VPN se conecte
+          if ! pgrep -x openvpn > /dev/null; then
+            echo "OpenVPN failed to start. Exiting..."
+            exit 1
+          fi
 
       - name: Conexion SSH y Despliegue # Conecta por SSH al servidor y despliega el proyecto
         uses: appleboy/ssh-action@v1
